version: '3'
services:
  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    container_name: smarthome_data_mysql
    ports:
      - 3306:3306
    tty: true
  app:
    build:
      context: .
    restart: always
    container_name: smarthome_app
    environment:
      - PORT_ENV=8080
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - db
    links:
      - db